title: Java Web and Linux Tutorials
description: > # this means to ignore newlines until "baseurl:"
  Tutorials for Spring Framework and Linux Os. It provides simple follow-up and walkthroughs videos.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Ilias Slimani # add your name
author-img: ilias-slimani.jpg # add your photo
about-author: I am a software engineer student, focusing on Java Technologies and Linux Operating System. Nowadays, I spend most of my free time learning and working with Spring Technologies and AngularJs4 . Always hungry to keep learning. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: ISlimani # add your Github handle
linkedin: # add your Linkedin handle
email: ilias.slimani@edu.uiz.ac.ma # add your Email address

# Disqus
discus-identifier: http-slimanitech-com # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
